# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgJoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('datatype', models.CharField(choices=[('T', 'text'), ('I', 'image'), ('V', 'vedio')], max_length=1)),
                ('source', models.URLField()),
                ('content', models.ImageField(upload_to='img/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextJoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('datatype', models.CharField(choices=[('T', 'text'), ('I', 'image'), ('V', 'vedio')], max_length=1)),
                ('source', models.URLField()),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VedioJoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('datatype', models.CharField(choices=[('T', 'text'), ('I', 'image'), ('V', 'vedio')], max_length=1)),
                ('source', models.URLField()),
                ('content', models.FileField(upload_to='vedio/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
