# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokelist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgjoke',
            name='datatype',
        ),
        migrations.RemoveField(
            model_name='textjoke',
            name='datatype',
        ),
        migrations.RemoveField(
            model_name='vediojoke',
            name='datatype',
        ),
        migrations.AlterField(
            model_name='imgjoke',
            name='source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='textjoke',
            name='source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='vediojoke',
            name='source',
            field=models.URLField(null=True),
        ),
    ]
