# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokelist', '0002_auto_20170307_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgjoke',
            name='source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='textjoke',
            name='source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vediojoke',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
